### ISSUE TITLE
Реализовать первичный CI/CD нашего приложения.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/Tabit#124]
# Зачем?

Необходимо, чтобы стала доступна документация извне.

# Как нужно делать?

Необходимо прописать:
- Dockerfile для сборки образа приложения. Пока достаточно самый простой запуск. Но зависимости брать с dev
- Написать action для сборки и загрузки образа на github packages. Пример ниже.
- Отдельно написать action для разворачивания приложения на VPS
- Обязательно провести предварительную настройку VPS. Необходимо создать пользователя dev_deploy. Выдать права sudo, установить докер и поместить его в группу. Доступ на сервер по SSH ключу.

пример CI для сборки:
```
name: Build and push Docker image

on:
  push:
    branches:
      - master
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image for Production
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/prod/prod.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image for Stage
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/stage/stage.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

пример CD на сервер:
```
 deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy changes on server
    needs: [pytest, build_and_push]
    runs-on: ubuntu-latest
    environment:
      name: prod_deploy
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Delete stage & dev
      run: |
        rm -r infra/stage
        rm -r infra/dev

    - name: Stopping old containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          STATUS="$(systemctl is-active our_service.service)"
          if [ "${STATUS}" = "active" ]; then
            sudo systemctl stop our_service.service
            echo "Stopping old containers"
          else
            echo "No active containers"
          fi

    - name: Copy infra via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "infra/"
        target: "${{ env.DEPLOY_PATH }}/infra"
        rm: true
        strip_components: 1
    - name: Execute commands on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ${{ env.DEPLOY_PATH }}
          touch .env

          echo "${{ secrets.ENV_FILE }}" > .env

          cd infra/prod/
          docker system prune --force

          sudo cp -f /home/production/our_service/infra/prod/our_service.service /etc/systemd/system/our_service.service
          sudo systemctl daemon-reload
          sudo systemctl start our_service.service

          sudo systemctl is-active --quiet our_service.service
          until [ $? -eq 0 ]; do
            echo "Waiting for our_service.service to be active..."
            sleep 5
            sudo systemctl is-active --quiet our_service.service
          done

          echo "our_service.service is active"

          docker exec our_service python manage.py collectstatic --noinput
          docker exec our_service python manage.py migrate
```

# Где?

infra/stage/stage.Dockerfile
infra/stage/docker-compose.stage.yaml
.github/workflows/build_and_push.yaml
.github/workflows/stage_deploy.yaml
