### ISSUE TITLE
Интеграция PGAdmin

### ISSUE THREAD

**Issue by AndreyZherdetskiy** [Studio-Yandex-Practicum/Tabit#154]
**Приоритет задачи: стандартный**

**Сложность задачи: легкая (решается стандартно, в соответствии с документацией)**

**Количество разработчиков для выполнения задачи: 1**

---

# Зачем?

*Интеграция PGAdmin в проект необходима для предоставления удобного графического интерфейса для администрирования и мониторинга PostgreSQL базы данных. Это решит проблему сложности ручного выполнения SQL-запросов через командную строку и упростит процесс отладки и анализа данных для разработчиков и администраторов.*

# Как нужно делать?

1. Создать отдельный Docker-контейнер с PGAdmin в `docker-compose.yml`
2. Настроить подключение к существующей PostgreSQL базе данных
3. Обеспечить безопасность доступа через настройку аутентификации
4. Интегрировать конфигурацию в CI/CD pipeline ([Issue по подключению первичного CI/CD](https://github.com/Studio-Yandex-Practicum/Tabit/issues/124), скоординировать работу по разработке, возможно предоставить часть кода)
5. Добавить документацию по использованию PGAdmin в проект
6. Протестировать работоспособность PGAdmin

Пример конфигурации:
```yaml
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secure_password
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend
```

# Где?

*Интеграция выполняется в docker-compose.yml проекта. Задействованные сервисы: PostgreSQL, PGAdmin. Ссылки на документацию:*

- [Официальная документация PGAdmin](https://www.pgadmin.org/docs/)
- [Docker образ PGAdmin](https://hub.docker.com/r/dpage/pgadmin4)
- [Пример конфигурации](https://github.com/postgres/pgadmin4)
